//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerceriaGit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compras
    {
        public int Id { get; set; }
        public int Id_Producto { get; set; }
        public int Cantidad { get; set; }
        public decimal Subtotal { get; set; }
        public decimal IVA { get; set; }
        public decimal Total { get; set; }
        public int Estado { get; set; }
    
        public virtual Productos Productos { get; set; }
    }
}
