//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerceriaGit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direcciones
    {
        public int Id { get; set; }
        public int Id_Usuario { get; set; }
        public string Calle { get; set; }
        public string Entidad { get; set; }
        public string Municipio { get; set; }
        public int Numero_Exterior { get; set; }
        public int Numero_Interior { get; set; }
        public int Codigo_Postal { get; set; }
        public string Referencias { get; set; }
        public int Estado { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
