//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerceriaGit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Envios
    {
        public int Id { get; set; }
        public int Id_Paqueteria { get; set; }
        public int Id_Venta { get; set; }
        public string Codigo_Rastreo { get; set; }
        public System.DateTime Fecha_Envio { get; set; }
        public System.DateTime Fecha_Estimada_Entrega { get; set; }
        public int Estado_Envio { get; set; }
        public Nullable<System.DateTime> Fecha_Entrega { get; set; }
        public int Estado { get; set; }
    
        public virtual Paqueterias Paqueterias { get; set; }
        public virtual Ventas Ventas { get; set; }
    }
}
