//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerceriaGit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido_Paterno { get; set; }
        public string Apellido_Materno { get; set; }
        public System.DateTime Fecha_Nacimiento { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public int Id_TipoUsuario { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Estado { get; set; }
    
        public virtual TipoUsuario TipoUsuario { get; set; }
    }
}
